apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .Values.nodeName }}-virtual-kubelet-config"
  namespace: {{ .Release.Namespace }}
data:
  InterLinkConfig.yaml: |
    {{- if .Values.interlink.socket }}
    InterlinkURL: {{ .Values.interlink.socket | quote }}
    InterlinkPort: {{ printf "%s-1" .Values.interlink.socket | quote }}
    {{- else }}
    InterlinkURL: {{ .Values.interlink.address | quote }}
    InterlinkPort: {{ .Values.interlink.port | quote }}
    {{- end }}
    {{- if .Values.interlink.kubernetesApiAddr }}
    KubernetesApiAddr: {{.Values.interlink.kubernetesApiAddr | quote }}
    {{- end }}
    {{- if .Values.interlink.kubernetesApiPort }}
    KubernetesApiPort: {{.Values.interlink.kubernetesApiPort | quote }}
    {{- end }}
    ExportPodData: {{ .Values.interlink.exportPodData }}
    VerboseLogging: true
    ErrorsOnlyLogging: false
    ServiceAccount: "{{ .Values.nodeName }}"
    Namespace: "{{ .Release.Namespace }}"
    VKTokenFile: {{ .Values.OAUTH.enabled | ternary "/opt/interlink/token" "/dev/null" }}
    CPU: "{{ .Values.virtualNode.CPUs }}"
    Memory: "{{ .Values.virtualNode.MemGiB }}Gi"
    Pods: "{{ .Values.virtualNode.Pods }}"
    HTTP:
      Insecure: {{ .Values.virtualNode.HTTP.Insecure }}
    KubeletHTTP:
      Insecure: {{ .Values.virtualNode.KubeletHTTP.Insecure }}
---
{{- if .Values.interlink.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .Values.nodeName }}-interlink-config"
  namespace: {{ .Release.Namespace }}
data:
  InterLinkConfig.yaml: |
    {{- if .Values.interlink.socket }}
    InterlinkAddress: {{ .Values.interlink.socket | quote }}
    {{- else }}
    InterlinkAddress: {{ .Values.interlink.address | quote }}
    InterlinkPort: {{ .Values.interlink.port | quote }}
    {{- end }}
    {{- if .Values.plugin.socket }}
    SidecarURL: {{ .Values.plugin.socket | quote }}
    {{- else }}
    SidecarURL: {{ .Values.plugin.address | quote }}
    SidecarPort: {{ .Values.plugin.port | quote }}
    {{- end }}
    VerboseLogging: true
    ErrorsOnlyLogging: false
    ExportPodData: {{ .Values.interlink.exportPodData }}
    DataRootFolder: /data/interlink
{{- end }}
---
{{- if .Values.plugin.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .Values.nodeName }}-plugin-config"
  namespace: {{ .Release.Namespace }}
data:
  plugin.yaml: |
    {{ .Values.plugin.config | indent 4 }}
{{- end }}
